runtime: nodejs18
instance_class: F2

env_variables:
  DATABASE_URL: "mysql://1lx5vhxphw0mhena5yev:pscale_pw_GZmJAPUSMsA394VDpB8py9pKZIaAXyvn2d7fVED7mlc@aws.connect.psdb.cloud/bibliotyper?sslaccept=strict"
