runtime: nodejs18
instance_class: F2

# env_variables:
#   DATABASE_URL: "postgresql://postgres:W47aqSYxNT23BZbSx5MG@synapse-db.cblrc8xihsp7.ap-southeast-1.rds.amazonaws.com:5432/Synapse?schema=public"
